DjangoBuhSite/apps/buh/urls.py
from django.urls import path

from . import views
from .models import Service

app_name = 'buh'
urlpatterns = [
	path('', views.Index.as_view(), name='index'),
    path('services/', views.Services.as_view(), name='services'),
    path('service_detail/<slug:slug>', views.Service_detail.as_view(), name='service_detail'),
    path('guarantee/', views.Guarantee.as_view(), name='guarantee'),
    path('contacts/', views.Contacts.as_view(), name='contacts'),
    path('get_service/', views.GetService.as_view(), name='get_service'),
    path('get_service/<slug:slug>', views.GetService.as_view(), name='get_service'),
    path('get_service/add_service', views.GetService.as_view(), name='add_service'),
	]

DjangoBuhSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('buh.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoBuhSite/apps/buh/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Service(models.Model):
    title = models.CharField('Название услуги', max_length=100)
    description = models.CharField('Описание', max_length=200)
    poster = models.ImageField('Постер', height_field=225)
    text = models.TextField('Текст')
    url = models.SlugField('url')
    publish = models.BooleanField('Опубликовать', default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('service_detail', kwargs = {'slug': self.url})

    def is_published(self):
        return True if self.publish else False

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'


class Image(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    title = models.CharField('Имя изображения', max_length=100)
    img = models.ImageField('Изображение')
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'


class SiteWrapper(models.Model):
    name = models.CharField('Название компании', max_length=100, default='BuhPro')
    show_about = models.BooleanField('Показывать блок About', default=True)
    about = models.CharField('Описание', max_length=500, default='Лучшие бухгалтерские услуги в Санкт-Петербурге.')
    footer_text = models.CharField('Текст снизу сайта', max_length=500, default='По всем вопросам обращайтесь по телефону или другим контактам')
    footer_link = models.CharField('Ссылка снизу сайта', max_length=500, default='Контакты')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Редактор сайта'


class Index(models.Model):
    title = models.CharField('Заголовок', max_length=100, default='BuhPro')
    description = models.CharField('Описание', max_length=500, default='')
    text = models.TextField('Текст', default='')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Стартовая страница'
        verbose_name_plural = 'Стартовые страницы'


class Guarantee(models.Model):
    title = models.CharField('Заголовок', max_length=100)
    text = models.TextField('Текст')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Гарантия'
        verbose_name_plural = 'Гарантии'

class Contact(models.Model):
    choices = [
        ('phone', 'Phone'),
        ('email', 'E-mail'),
        ('other', 'Other'),
        ]
    title = models.CharField('Заголовок', max_length=50)
    type = models.CharField('Тип контакта', choices=choices, max_length=50)
    text = models.CharField('Текст', max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

class ServiceRequest(models.Model):
    name = models.CharField('Имя', max_length=50)
    phone = models.CharField('Телефон', max_length=50)
    email = models.EmailField('E-mail', blank=True)
    service = models.ForeignKey(Service, models.DO_NOTHING, verbose_name='Услуга')
    description = models.TextField('Описание')
    date = models.DateTimeField('Дата', default=timezone.now())
    is_processed = models.BooleanField('Обработано', default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Запрос услуги'
        verbose_name_plural = 'Запрос услуг'

DjangoBuhSite/apps/buh/forms.py
from django.forms import ModelForm

from .models import ServiceRequest

class ServiceForm(ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ('name', 'phone', 'email', 'service', 'description')

DjangoBuhSite/apps/buh/views.py
from django.urls import reverse
from django.shortcuts import render
from django.views import View
from django.http.response import HttpResponseRedirect

from . import models
from . import forms


class Index(View):
    def get(self, request):
        return render(request, 'buh/index.html')


class Services(View):
    def get(self, request):
        services = models.Service.objects.filter(publish=True)
        return render(request, 'buh/services.html', {'services': services})
    

class Service_detail(View):
    def get(self, request, slug):
        service = models.Service.objects.get(url=slug)
        return render(request, 'buh/service_detail.html', {'service': service})


class Guarantee(View):
    def get(self, request):
        return render(request, 'buh/guarantee.html')


class Contacts(View):
    def get(self, request):
        return render(request, 'buh/contacts.html')


class GetService(View):
    def get(self, request, slug=None):
        services = models.Service.objects.filter(publish=True)
        args = [request, 'buh/get_service.html', {'services': services}]
        if slug is not None:
            service = models.Service.objects.get(url=slug)
            args[2]['service'] = service
        return render(*args)

    def post(self, request, slug):
        service = models.Service.objects.get(title=request.POST['service'])
        data = request.POST.copy()
        data['service'] = service
        form = forms.ServiceForm(data)
        if form.is_valid():
            form = form.save()

        slug = service.url
        return HttpResponseRedirect(reverse('buh:service_detail', args=(slug,)))

DjangoBuhSite/templates/buh/contacts.html
{% extends "wrapper.html" %}

{% block title %}Контакты|Бухгaлтерские услуги{% endblock title %}

{% block content %}
<br />
    <div class="container">
        Какие то контакты
    </div>
<br />
{% endblock content %}

DjangoBuhSite/templates/buh/get_service.html
{% extends "wrapper.html" %}

{% block title %}Заказать услугу|Бухгaлтерские услуги{% endblock title %}

{% block content %}
<br />

<form action="{% url "buh:add_service" %}" method="POST" id="service_form">

    <div class="container">

        <div class="row">

            <div class="col-md-6 text-right">

                <label for="name">Введите имя*</label><br /><br />

                <label for="phone">Введите номер телефона*</label><br /><br />

                <label for="email">Введите E-mail</label><br /><br />

                <label for="service">Выберите услугу</label><br /><br />

                <label for="description">Описание</label><br /><br />


            </div>

            <div class="col-md-6 text-left">

                {% csrf_token %}
                <input required placeholder="Ваше имя" id="name" name="name" /><br /><br />

                <input required placeholder="Ваш номер" id="phone" name="phone" /><br /><br />

                <input placeholder="Ваш E-mail" id="email" name="email" /><br /><br />

                <select required name="service" size="1" id="service">
                    {% for service in services %}
                    <option>{{service.title}}</option>
                    {% endfor %}
                </select><br /><br />

                <textarea rows="5" cols="30" id="description" name="description"></textarea><br /><br />



            </div>
        </div>
    </div>
    
    <div class="container text-center">
        <button type="submit">Заказать</button><br />
        <em>Мы свяжемся с вами в ближайшее время</em>
    </div>
</form>

<br />
{% endblock content %}

DjangoBuhSite/templates/buh/guarantee.html
{% extends "wrapper.html" %}

{% block title %}Гарантии|Бухгaлтерские услуги{% endblock title %}

{% block content %}
    <div class="container">
        Какие то гарантии
    </div>
{% endblock content %}

DjangoBuhSite/templates/buh/index.html
{% extends "wrapper.html" %}
{% load buh_tag %}
{% index_data as Index %}

{% block title %}Главная|Бухгaлтерские услуги{% endblock title %}


{% block upper %}
{% upper_section_tag %}
{% endblock upper %}


{% block content %}
<div class="container">
    <p>{{Index.text}}</p>
</div>
{% endblock content %}

DjangoBuhSite/templates/buh/service_detail.html
{% extends "wrapper.html" %}

{% block title %}Услуги|Бухгaлтерские услуги{% endblock title %}

{% block content %}
    <div class="container">
        <br /><h2>{{service.title}}</h2>
        <p>{{service.text|safe|linebreaks}}</p>
        <img src="{{service.image_set.get.img.url}}" height="400" />
        <br /><br /><a href="{% url "buh:get_service" %}">Заказать услугу</a><br />
    </div>
<br />
{% endblock content %}

DjangoBuhSite/templates/buh/services.html
{% extends "wrapper.html" %}

{% block title %}Услуги|Бухгaлтерские услуги{% endblock title %}

{% block content %}


<div class="container">

    <div class="row">

        {% if services %}

        {% for service in services %}

        <div class="col-md-6">
            <div class="card mb-4 shadow-sm">
                <a href="{% url "buh:service_detail" service.url %}" class="text-white"><img src="{{service.image_set.get.img.url}}" width="100%" height="225" ></a>
                <div class="card-body">
                    <a href="{% url "buh:service_detail" service.url %}" class="text-white">{{service.title}}</a>
                    <p class="card-text">{{service.text|safe|linebreaks}}</p>
                </div>
            </div>
        </div>

        {% endfor %}

        {% endif %}
    </div>
</div>


{% endblock content %}

DjangoBuhSite/templates/buh/tags/upper_section.html
{% load buh_tag %}
{% index_data as Index %}

<section class="jumbotron text-center">
    <div class="container">
        <h1>{{Index.title}}</h1>
        <p class="lead text-muted">{{Index.description}}</p>
        <p>
            <a href="{% url "buh:services" %}" class="btn btn-primary my-2">Услуги</a>
            <a href="{% url "buh:get_service" %}" class="btn btn-secondary my-2">Заказать услугу</a>
        </p>
    </div>
</section>

DjangoBuhSite/templates/includes/footer.html
{% load buh_tag %}
{% get_site_wrapper_data as SiteWrapper %}

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Наверх</a>
        </p>
        <p>{{SiteWrapper.footer_text}}</p>
        <p><a href="{% url "buh:contacts" %}">{{SiteWrapper.footer_link}}</a></p>
    </div>
</footer>

DjangoBuhSite/templates/includes/header.html
{% load static %}
{% load buh_tag %}
{% get_site_wrapper_data as SiteWrapper %}

<header>
    <div class="bg-dark collapse" id="navbarHeader" style="">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    {% if SiteWrapper.show_about %}
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">{{SiteWrapper.about}}</p>
                    {% endif %}
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <ul class="list-unstyled">
                        <li><a href="{% url "buh:index" %}" class="text-white"><h4>Главная</h4></a></li>
                        <li><a href="{% url "buh:services" %}" class="text-white"><h4>Услуги</h4></a></li>
                        <li><a href="{% url "buh:guarantee" %}" class="text-white"><h4>Гарантии</h4></a></li>
                        <li><a href="{% url "buh:contacts" %}" class="text-white"><h4>Контакты</h4></a></li>
                        <li><a href="{% url "buh:get_service" %}" class="text-white"><h4>Заказать услугу</h4></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="{% url "buh:index" %}" class="navbar-brand d-flex align-items-center">
                <img src="{% static "unnamed.png" %}" width="50" height="50" fill="none" />
                <strong>{{SiteWrapper.name}}</strong>
            </a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

DjangoBuhSite/templates/wrapper.html
<!doctype html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>{% block title %}Бухгaлтерские услуги{% endblock title %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/album/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
</head>


<body>

    {% include "includes/header.html" %}

    {% block upper %}
    {% endblock upper %}

    <main role="main">

        <div class="album py-5 bg-light">
            {% block content %}
            {% endblock content %}
        </div>

    </main>

    {% include "includes/footer.html" %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!---->
</body>
</html>